### ISSUE TITLE
[PE-D][Tester C] Incorrect error message (should be email format error)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-2/tp#149]
![image.png](https://raw.githubusercontent.com/dreammac3816547290/ped/main/files/4127e6fe-6bf8-48c1-b82a-702e987f448f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: dreammac3816547290/ped#8

**Comment by hoang227** [comment]
if john doe doesnt exist in the addressbook, this should work.
